### ISSUE TITLE
email / link for contact buttons

### ISSUE THREAD

**Issue by derekeder** [datamade/councilmatic-splash#1]
The 'contact us' stuff needs to be wired up. Should we setup an email info@councilmatic.org?

cc: @davidmooreppf

**Comment by davidmooreppf** [comment]
Yeah whatever's feasible given your time - I'd love to have: info@, david@, and asher@, but I know that's a bit of setup.

**Comment by derekeder** [comment]
Rad - thanks for the quick replies.

info@councilmatic.org is setup. Just sent a test email out.
